### Create
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota3",
    "model": "Corolla",
    "year": 1970,
    "mileage": 100,
    "lng": 0,
    "lat": 0,
    "price": 50000
}

### Approve an existing report
PATCH http://localhost:3000/reports/9
Content-Type: application/json

{
    "approved": true
}